version: '3.7'

services:
  database:
    image: postgres
    ports:
      - 5432:5432

  app:
    container_name: curso-ignite-compose
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
